// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jquery.Models;

namespace jquery.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220821090730_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("jquery.Models.kisiler", b =>
                {
                    b.Property<int>("Kisi_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("kisi_isim")
                        .HasColumnType("text");

                    b.Property<string>("kisi_soyad")
                        .HasColumnType("text");

                    b.Property<int>("kisi_yas")
                        .HasColumnType("int");

                    b.HasKey("Kisi_id");

                    b.ToTable("kisilers");
                });
#pragma warning restore 612, 618
        }
    }
}
